---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: nioctib-k8s
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: master
  url: https://github.com/liuhongchao/nioctib-k8s.git

